name: Automatically update Gale commit hash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Leaf repository
        uses: actions/checkout@main
        with:
          path: 'Leaf'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grant execute permission for gradlew
        run: |
          cd Leaf
          git config --global user.name "Dreeam"
          git config --global user.email 61569423+Dreeam-qwq@users.noreply.github.com
          chmod +x gradlew

      - uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version:  21

      - name: Running tests before push
        run: |
          cd Leaf
          if ! git diff --quiet; then
            echo "Running tests...."
            ./gradlew applyPatches
            ./gradlew createMojmapPaperclipJar
            ./gradlew rebuildPatches
          fi

      - name: Check for changes and write to repository
        run: |
          cd Leaf
          if ! git diff --quiet; then
            echo "Writing to repo....."
            git add --all
            chmod +x ./scripts/upstreamCommit.sh
            ./scripts/upstreamCommit.sh --gale $CURR_GALE_REF
            git push
          else
            echo "No changes to commit."
          fi
        env: {}